repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
      - id: ruff
        args: ["check", "--select", "F401,I", "--fix", "--exit-non-zero-on-fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-xml
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-added-large-files
        args: ["--maxkb=20000", "--enforce-all"]
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: debug-statements
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-ruff
        additional_dependencies: [ruff==0.2.1]
        args: ["check", "--select", "F401,I", "--fix", "--exit-non-zero-on-fix"]
      - id: nbqa-ruff-format
        additional_dependencies: [ruff==0.2.1]
